apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: observability
data:
  kibana.yml: |
    server.host: "localhost"
    elasticsearch.hosts: ["http://localhost:30200"]
    # Elastic SA Token for Kibana
    elasticsearch.password: "QUFFQUFXVnNZWE4wYVdNdmEybGlZVzVoTDJ0cFltRnVZUzEwYjJ0bGJqcEJTbGw1TWtobGRsUk5aVlJKV0ZGWFZTMUhiVkpSCg=="
