apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: observability
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    elasticsearch.hosts: ["http://elasticsearch.observability.svc.cluster.local:9200"]
    # Elastic SA Token for Kibana
    #elasticsearch.username: "elastic"
    #elasticsearch.serviceAccountToken: "AAEAAWVsYXN0aWMva2liYW5hL25ldy10b2tlbjprdG55U2F2VVR1ZXdsbThqZVk3R0dB"
