apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kibana-es-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: elastisearch-service-account-token          # This Kubernetes Secret will be created
    creationPolicy: Owner
  data:
    - secretKey: serviceAccountToken     # Key in the final K8s Secret
      remoteRef:
        key: elastisearch         # Path in Vault
        property: service-account-token   # Field name in Vault