apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-secret
  namespace: observability
  annotations:
    # Create this secret before the pre-install Job (weight 0) runs.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: elasticsearch-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: elastisearch
        property: kibana-token
