apiVersion: batch/v1
kind: Job
metadata:
  name: create-kibana-token
  namespace: observability
spec:
  template:
    spec:
      serviceAccountName: kibana-token-sa
      restartPolicy: Never
      containers:
      - name: create-token
        image: elastic/kibana:9.1.7
        command: ["/usr/share/kibana/node/bin/node"]
        args: ["/usr/share/kibana/helm-scripts/manage-es-token.js","clean"]
        env:
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: username
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-credentials
              key: password
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: /usr/share/kibana/config/certs/ca.crt
        volumeMounts:
        - name: scripts
          mountPath: /usr/share/kibana/helm-scripts
        - name: certs
          mountPath: /usr/share/kibana/config/certs
      volumes:
      - name: scripts
        configMap:
          name: kibana-helm-scripts
          defaultMode: 0755
      - name: certs
        secret:
          secretName: elasticsearch-certs