apiVersion: batch/v1
kind: Job
metadata:
  name: create-kibana-token
  namespace: observability
spec:
  template:
    spec:
      serviceAccountName: kibana-token-sa
      restartPolicy: Never
      containers:
      - name: create-token
        image: node:20-alpine
        command: ["node"]
        args:
          - /helm-scripts/manage-es-token.js
          - create
        env:
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: elasticsearch-secret
              key: password
        # - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
        #   value: /usr/share/kibana/config/certs/ca.crt
        volumeMounts:
        - name: scripts
          mountPath: /helm-scripts
        # - name: certs
        #   mountPath: /usr/share/kibana/config/certs
      volumes:
      - name: scripts
        configMap:
          name: kibana-helm-scripts
          defaultMode: 0755
      # - name: certs
      #   secret:
      #     secretName: elasticsearch-certs