apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  ports:
  - name: jenkins-http
    port: {{ .Values.portNumber | int }}
    targetPort: {{ .Values.portNumber | int }}
    nodePort: {{ .Values.nodePortNumber | int }}
  - name: jenkins-agent
    port: {{ .Values.tunnelPortNumber | int }}
    targetPort: {{ .Values.tunnelPortNumber | int }}
  selector:
    app: {{ .Values.name }}
  type: NodePort


# Note: Have to add in jenkins url & tunnel in Kubernetes cloud configuration
# http://jenkins.jenkins.svc.cluster.local:8080
# jenkins.jenkins.svc.cluster.local:50000