apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-service-account
  namespace: {{ .Values.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access
  namespace: {{ .Values.name }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-binding
  namespace: {{ .Values.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-service-account
  namespace: {{ .Values.name }}
roleRef:
  kind: Role
  name: pod-access
  apiGroup: rbac.authorization.k8s.io
