apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch-secret
  namespace: observability
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: elasticsearch-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: elastisearch
        property: kibana-token
