apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: "global-credentials" # KV engine path
      version: "v2"
      auth:
        # tokenSecretRef:
        #   namespace: observability
        #   name: vault-token # Kubernetes Secret containing the token
        #   key: token
        appRole:
          path: "approle"
          roleId: "5eaef715-ad53-d2e3-c701-48666fe5a120"
          secretRef:
            name: vault-secret-id
            key: secretId