apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://localhost:30082"
      path: "global-credentials" # KV engine path
      version: "v2"
      auth:
        tokenSecretRef:
          namespace: metadata.namespace
          name: vault-token # Kubernetes Secret containing the token
          key: token
