apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLkNBRVNJRC02VGJaT0RPYzdlNWxoSGpCN1lXRnNKLTVadnpraFdBRWdRUXlER01PR0doNEtIR2gyY3k1dE9YbFhkbWRQYURKT1JVWnBlREZRTmxSRWJuZzRlRmsK