apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: aHZzLkNBRVNJS0twZVZhSWlkSjRIY1gtZWpPUDFYRTFTSmQ0Tk9XV3lhUFRqczhXVWI1T0doNEtIR2gyY3k1S1EySkROSFpyYjBKeVNXbGlaelYwWW0wNGIwdzFZalE=