destinationServer: https://kubernetes.default.svc
selfHeal: true
prune: true
project: infrastructure
Application:
  - name: jenkins-appofapps
    namespace: jenkins
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/00-Project-Jenkins
  - name: sonarqube-appofapps
    namespace: sonarqube
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/01-Project-SonarQube
  - name: observability-appofapps
    namespace: observability
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/02-Project-Observability
  - name: keycloak-appofapps
    namespace: keycloak
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/03-Project-Keycloak
  - name: loki-appofapps
    namespace: observability
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/04-Project-Loki
  - name: promtail-appofapps
    namespace: observability
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/05-Project-Promtail
  - name: grafana-appofapps
    namespace: observability
    projectSource: 
      url: https://github.com/ankuradarsh/Infra-Setup.git
      path: 02-apps-cm/templates/06-Project-Grafana


