apiVersion: v2
name: 04-project-loki
version: 0.0.1
dependencies:
  - name: loki
    version: 13.1.2
    # repository: https://grafana.github.io/helm-charts
    repository: https://grafana-community.github.io/helm-charts