backend:
  replicas: 1

ui:
  enabled: true

read:
  replicas: 1

write:
  replicas: 1


# Completely disable self-monitoring and the problematic CRDs
monitoring:
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: false     # disable if you don't use Prometheus Operator
  dashboards:
    enabled: true      # safe to keep
  rules:
    enabled: true      # safe to keep (PrometheusRule)

# Extra safety - disable the subchart that brings the big CRDs
grafana-agent-operator:
  enabled: false