loki:
  loki:
    deploymentMode: SingleBinary
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem
      bucketNames:
        chunks: chunks
        ruler: ruler
        admin: admin
      filesystem:
        directory: /var/loki/chunks
    useTestSchema: true

  singleBinary:
    enabled: true
    replicas: 1

  write:
    enabled: true
    replicas: 1

  read:
    enabled: true
    replicas: 1

  backend:
    enabled: true
    replicas: 1

  chunksCache:
    enabled: false

  resultsCache:
    enabled: false

  test:
    enabled: false