grafana:

  # =========================
  # Custom Image (IMPORTANT)
  # =========================
  image:
    registry: docker.io   # change if using private registry
    repository: grafana/grafana
    tag: 12.4.3
    pullPolicy: IfNotPresent

  imagePullSecrets: []
  
  adminUser: admin
  adminPassword: admin123   # move to Vault later

  initChownData:
    enabled: false
    securityContext:
      readOnlyRootFilesystem: false
      runAsNonRoot: false
      runAsUser: 0
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        add:
          - CHOWN
        drop:
          - ALL

  securityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  service:
    type: ClusterIP
    port: 80

  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

  # datasources:
  #   datasources.yaml:
  #     apiVersion: 1
  #     datasources:
  #       - name: Loki
  #         type: loki
  #         access: proxy
  #         url: http://loki-appofapps-gateway.observability.svc.cluster.local
  #         isDefault: true

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL

    datasources:
      enabled: true
      label: grafana_datasource

  # =========================
  # Grafana Config
  # =========================
  grafana.ini:
    server:
      root_url: https://grafana.your-domain.com
    security:
      allow_embedding: true
    users:
      auto_assign_org: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


  env:
    GF_LOG_LEVEL: info


dashboards:
  kubernetes-pods:
    folder: "Kubernetes"
    file: dashboards/kubernetes-pods.json